spring:
  application:
    name: Travel-ai-agent
  # 临时注释掉，便于开发调试和部署（实际填写 PgVector 数据库信息）
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  ai:
    dashscope:
      apikey: "sk-xxxxx"

      chat:
        options:
          model: qwen-max
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shandian.travelaiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
# 谷歌searchAPI
search-api:
  api-key: xxxxxxx